receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15

  resource:
    attributes:
      - key: service.name
        action: upsert
        from_attribute: service.name
      - key: deployment.environment
        value: staging
        action: insert
      - key: job
        value: unity-dms-api
        action: insert

  attributes:
    actions:
      - key: http.route
        action: upsert
        from_attribute: http.target
      - key: net.host.name
        action: delete
      - key: net.host.port
        action: delete
      - key: loki.attribute.labels
        value: service.name, level, job
        action: insert
      - key: loki.format
        value: json
        action: insert

exporters:
  # Traces to Tempo
  otlp/tempo:
    endpoint: tempo:4417
    tls:
      insecure: true


  prometheusremotewrite:
    # Use the /api/v1/write endpoint of your Prometheus server
    endpoint: "http://prometheus:9090/api/v1/write"
    timeout: 30s
    resource_to_telemetry_conversion:
      enabled: true


  # Metrics to Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"
    resource_to_telemetry_conversion:
      enabled: true
    const_labels:
      exporter: "otlp"

  # Logs to Loki using OTLP HTTP
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  # Debug exporter (useful for troubleshooting)
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  telemetry:
    metrics:
      level: none

  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource, attributes]
      exporters: [otlp/tempo]

    metrics:
      receivers: [otlp]
#      processors: [memory_limiter, batch, resource]
      processors: [memory_limiter, batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource, attributes]
      exporters: [otlphttp/loki]
